package com.microanswer.api.bean.model;

import com.microanswer.api.bean.base.BasePhonemp3app;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Phonemp3app extends BasePhonemp3app<Phonemp3app> {
	public static final Phonemp3app dao = new Phonemp3app().dao();
}
