package com.microanswer.api.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePhonemp3app<M extends BasePhonemp3app<M>> extends Model<M> implements IBean {

    public M setId(java.lang.Object id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Object getId() {
        return get("id");
    }

    public M setVersion(java.lang.Object version) {
        set("version", version);
        return (M) this;
    }

    public java.lang.Object getVersion() {
        return get("version");
    }

    public M setLink(java.lang.Object link) {
        set("link", link);
        return (M) this;
    }

    public java.lang.Object getLink() {
        return get("link");
    }

    public M setName(java.lang.Object name) {
        set("name", name);
        return (M) this;
    }

    public java.lang.Object getName() {
        return get("name");
    }

    public M setSize(java.lang.Object size) {
        set("size", size);
        return (M) this;
    }

    public java.lang.Object getSize() {
        return get("size");
    }


    public M setCreatedat(java.lang.Object createdat) {
        set("createdat", createdat);
        return (M) this;
    }

    public java.lang.Object getCreatedat() {
        return get("createdat");
    }


    public M setUpdateat(java.lang.Object updateat) {
        set("updateat", updateat);
        return (M) this;
    }

    public java.lang.Object getUpdateat() {
        return get("updateat");
    }


    public M setNewfunction(java.lang.Object newfunction) {
        set("newfunction", newfunction);
        return (M) this;
    }

    public java.lang.Object getNewfunction() {
        return get("newfunction");
    }


}
